package view;

import data.Produto;
import data.ProdutoDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author wande
 */
public class ProdutoFrame extends javax.swing.JFrame {

    /**
     * Creates new form Produto
     */
    public ProdutoFrame() {
        initComponents();
        this.preencherTabela("");
        centralizarJanela();
    }

    private void centralizarJanela() {
        Dimension dimensaoTela = Toolkit.getDefaultToolkit().getScreenSize();
        int larguraTela = dimensaoTela.width;
        int alturaTela = dimensaoTela.height;

        int larguraJanela = this.getSize().width;
        int alturaJanela = this.getSize().height;

        int posX = (larguraTela - larguraJanela) / 2;
        int posY = (alturaTela - alturaJanela) / 2;

        this.setLocation(posX, posY);
    }

    private void limparTela() {
        txtnome.setText("");
        txttamanho.setText("");
        txtdescricao.setText("");
        txtquantidade.setText("");
        txtvalor.setText("");
    }

    private void preencherTabela(String filtro) {

        ProdutoDAO dao = new ProdutoDAO();
        boolean status = dao.conectar();

        if (status == false) {
            JOptionPane.showMessageDialog(null, "erro de conexão");
        } else {
            List<Produto> listaProduto = dao.listagem(filtro);
            DefaultTableModel tabelaProduto = (DefaultTableModel) tblproduto.getModel();
            tblproduto.setRowSorter(new TableRowSorter(tabelaProduto));
            tabelaProduto.setNumRows(0);

            for (Produto p : listaProduto) {
                Object[] obj = new Object[]{
                    p.getId(),
                    p.getNome(),
                    p.getTamanho(),
                    p.getDescricao(),
                    p.getQuantidade(),
                    p.getValor()};
                tabelaProduto.addRow(obj);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblnomeproduto = new javax.swing.JLabel();
        lbltamanho = new javax.swing.JLabel();
        lbldescrição = new javax.swing.JLabel();
        lblvalor = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txttamanho = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        lblquantidade = new javax.swing.JLabel();
        txtquantidade = new javax.swing.JTextField();
        btnlimpar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblnomeproduto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblnomeproduto.setText("Nome do Produto:");

        lbltamanho.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbltamanho.setText("Tamanho:");

        lbldescrição.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbldescrição.setText("Descrição:");

        lblvalor.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblvalor.setText("Valor:");

        btnsalvar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnexcluir.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnalterar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        lblquantidade.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblquantidade.setText("Quantidade:");

        btnlimpar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblquantidade)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltamanho)
                            .addComponent(lblnomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldescrição)))
                    .addComponent(lblvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalvar)
                .addGap(18, 18, 18)
                .addComponent(btnexcluir)
                .addGap(18, 18, 18)
                .addComponent(btnalterar)
                .addGap(18, 18, 18)
                .addComponent(btnlimpar)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomeproduto)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltamanho)
                    .addComponent(txttamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescrição)
                    .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblquantidade)
                    .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvalor)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalvar)
                    .addComponent(btnexcluir)
                    .addComponent(btnalterar)
                    .addComponent(btnlimpar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblproduto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tblproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tamanho", "Descrição", "Quantidade", "Valor"
            }
        ));
        tblproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprodutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproduto);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed

        int id;
        ProdutoDAO dao = new ProdutoDAO();
        boolean status = dao.conectar();
        if (status == false) {
            JOptionPane.showMessageDialog(null, "erro de conexão");
        } else {
            int selectedRow = tblproduto.getSelectedRow();
            if (selectedRow != -1) {

                id = Integer.parseInt(tblproduto.getValueAt(selectedRow, 0).toString());
                status = dao.excluir(id);
            }

            if (status == true) {
                JOptionPane.showMessageDialog(null, "Produto Excluido com Sucesso!");
                preencherTabela("");
                limparTela();

                btnexcluir.setEnabled(false);
                btnalterar.setEnabled(false);
                btnsalvar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Erro na exclusão do produto!");

            }
            dao.desconectar();

        }


    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        Produto produto = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        boolean status;
        int resposta;

        try {

            String nome = txtnome.getText();
            String tamanho = txttamanho.getText();
            String descricao = txtdescricao.getText();
            String quantidade = txtquantidade.getText();
            String valor = txtvalor.getText();

            status = dao.conectar();

            if (!status) {
                JOptionPane.showMessageDialog(null, "Erro de conexão");
                return;
            }

            produto.setNome(nome);
            produto.setTamanho(tamanho);
            produto.setDescricao(descricao);
            produto.setQuantidade(quantidade);
            produto.setValor(valor);

            resposta = dao.salvar(produto);

            if (resposta == 1) {
                JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso");
                preencherTabela("");
                limparTela();

            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar o Produto");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {

            dao.desconectar();

        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void tblprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprodutoMouseClicked
        int linhaSelecionada = tblproduto.getSelectedRow();
        if (linhaSelecionada != -1) {

            String id = tblproduto.getValueAt(linhaSelecionada, 0).toString();
            String nome = tblproduto.getValueAt(linhaSelecionada, 1).toString();
            String tamanho = tblproduto.getValueAt(linhaSelecionada, 2).toString();
            String descricao = tblproduto.getValueAt(linhaSelecionada, 3).toString();
            String quantidade = tblproduto.getValueAt(linhaSelecionada, 4).toString();
            String valor = tblproduto.getValueAt(linhaSelecionada, 5).toString();

            txtnome.setText(nome);
            txttamanho.setText(tamanho);
            txtdescricao.setText(descricao);
            txtquantidade.setText(quantidade);
            txtvalor.setText(valor);

            btnexcluir.setEnabled(true);
            btnalterar.setEnabled(true);
            btnsalvar.setEnabled(false);
    }//GEN-LAST:event_tblprodutoMouseClicked
    }
    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed

        ProdutoDAO dao = new ProdutoDAO();
        boolean status;
        int resposta;

        int selectedRow = tblproduto.getSelectedRow();
        if (selectedRow != -1) {
            int id = Integer.parseInt(tblproduto.getValueAt(selectedRow, 0).toString());

            Produto produto = new Produto();
            produto.setId(id);
            produto.setNome(txtnome.getText());
            produto.setTamanho(txttamanho.getText());
            produto.setDescricao(txtdescricao.getText());
            produto.setQuantidade(txtquantidade.getText());
            produto.setValor(txtvalor.getText());

            status = dao.conectar();

            status = dao.conectar();

            if (!status) {
                JOptionPane.showMessageDialog(null, "Erro de conexão");
                return;
            }

            resposta = dao.alterar(produto);

            if (resposta == 1) {
                JOptionPane.showMessageDialog(null, "Produto alterado com sucesso");
                preencherTabela("");
                limparTela();

            } else {
                JOptionPane.showMessageDialog(null, "Erro ao alterar o produto");

            }

            dao.desconectar();

        }

    }//GEN-LAST:event_btnalterarActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        txtnome.setText("");
        txttamanho.setText("");
        txtdescricao.setText("");
        txtquantidade.setText("");
        txtvalor.setText("");
    }//GEN-LAST:event_btnlimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldescrição;
    private javax.swing.JLabel lblnomeproduto;
    private javax.swing.JLabel lblquantidade;
    private javax.swing.JLabel lbltamanho;
    private javax.swing.JLabel lblvalor;
    private javax.swing.JTable tblproduto;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtquantidade;
    private javax.swing.JTextField txttamanho;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
